# Generated by Django 5.2.5 on 2025-08-31 14:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=200)),
                ('primary_contact_first_name', models.CharField(max_length=100)),
                ('primary_contact_last_name', models.CharField(max_length=100)),
                ('primary_official_email', models.EmailField(max_length=254)),
                ('primary_phone_number', models.CharField(max_length=20)),
                ('secondary_contact_first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('secondary_contact_last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('secondary_official_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('secondary_phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('brand_vision', models.TextField()),
                ('brand_mission', models.TextField()),
                ('brand_core_values', models.TextField()),
                ('brand_visual_verbal_dna_guidelines', models.URLField(blank=True, null=True)),
                ('brand_website', models.URLField(blank=True, null=True)),
                ('brand_presence', models.TextField(blank=True, null=True)),
                ('website_traffic_kpis', models.TextField(blank=True, null=True)),
                ('instagram_reach_kpis', models.TextField(blank=True, null=True)),
                ('google_sepr_rank_kpis', models.TextField(blank=True, null=True)),
                ('review_rating_kpis', models.TextField(blank=True, null=True)),
                ('social_media_posts_per_week_kpis', models.TextField(blank=True, null=True)),
                ('videos_per_week_kpis', models.TextField(blank=True, null=True)),
                ('shorts_per_week_kpis', models.TextField(blank=True, null=True)),
                ('strengths', models.TextField(blank=True, null=True)),
                ('weaknesses', models.TextField(blank=True, null=True)),
                ('opportunities', models.TextField(blank=True, null=True)),
                ('threats', models.TextField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('tiktok', models.URLField(blank=True, null=True)),
                ('youtube', models.URLField(blank=True, null=True)),
                ('pinterest', models.URLField(blank=True, null=True)),
                ('snapchat', models.URLField(blank=True, null=True)),
                ('telegram', models.URLField(blank=True, null=True)),
                ('medium', models.URLField(blank=True, null=True)),
                ('quora', models.URLField(blank=True, null=True)),
                ('reddit', models.URLField(blank=True, null=True)),
                ('tumblr', models.URLField(blank=True, null=True)),
                ('threads', models.URLField(blank=True, null=True)),
                ('bluesky', models.URLField(blank=True, null=True)),
                ('whatsapp_business', models.URLField(blank=True, null=True)),
                ('website_blogs', models.URLField(blank=True, null=True)),
                ('top_10_partners', models.TextField(blank=True, help_text='List of top 10 partners', null=True)),
                ('top_10_competitors', models.TextField(blank=True, help_text='List of top 10 competitors', null=True)),
                ('additional_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Brand Profile',
                'verbose_name_plural': 'Brand Profiles',
            },
        ),
    ]
