# Generated by Django 5.2.5 on 2025-09-08 08:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='brandprofile',
            name='is_public_enabled',
            field=models.BooleanField(default=False, help_text='Allow public access to dashboard via shareable link'),
        ),
        migrations.AddField(
            model_name='brandprofile',
            name='public_link_created_at',
            field=models.DateTimeField(blank=True, help_text='When public access was first enabled', null=True),
        ),
        migrations.AddField(
            model_name='brandprofile',
            name='public_link_created_by',
            field=models.ForeignKey(blank=True, help_text='Manager who enabled public access', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_public_links', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='brandprofile',
            name='public_uuid',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
