# Generated by Django 5.2.5 on 2025-08-31 15:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashtag', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('core_trading_forex', 'Core Trading & Forex'), ('trading_education_strategy', 'Trading Education & Strategy'), ('technology_platform', 'Technology & Platform'), ('regional_location', 'Regional & Location Based'), ('business_professional', 'Business & Professional'), ('social_community', 'Social & Community'), ('action_engagement', 'Action & Engagement')], max_length=30)),
                ('usage_context', models.TextField()),
                ('platform_suitability', models.CharField(max_length=200)),
                ('popularity_score', models.IntegerField(default=1)),
                ('best_posting_time', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['-popularity_score', 'hashtag'],
            },
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('past_status', models.CharField(choices=[('active', 'Active'), ('not_active', 'Not Active'), ('not_available', 'Not Available'), ('already_in_place', 'Already in Place')], max_length=20)),
                ('committed_content', models.IntegerField(default=0)),
                ('drafted_content', models.IntegerField(default=0)),
                ('published_content', models.IntegerField(default=0)),
                ('content_link', models.URLField(blank=True, null=True)),
                ('category', models.CharField(choices=[('digital_identity', 'Digital Identity'), ('professional_writing', 'Professional Writing'), ('informational_content', 'Informational Content'), ('local_business', 'Local Business'), ('professional_network', 'Professional Network'), ('long_form_video', 'Long-Form Video'), ('short_form_video', 'Short-Form Video'), ('visual_content', 'Visual Content'), ('real_time_social', 'Real-Time Social'), ('social_community', 'Social Community'), ('creative_blogging', 'Creative Blogging'), ('micro_blogging', 'Micro-Blogging'), ('qa_content', 'Q&A Content'), ('discussion_forum', 'Discussion Forum'), ('direct_marketing', 'Direct Marketing'), ('live_streaming', 'Live Streaming'), ('authentic_visual', 'Authentic Visual'), ('professional_video', 'Professional Video'), ('video_content', 'Video Content')], max_length=30)),
                ('primary_content_types', models.TextField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BrandPlatformStrategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_selected', models.BooleanField(default=False)),
                ('custom_committed_content', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.platform')),
            ],
            options={
                'unique_together': {('user', 'platform')},
            },
        ),
        migrations.CreateModel(
            name='ContentPiece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content_type', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('drafted', 'Drafted'), ('reviewed', 'Reviewed'), ('published', 'Published')], default='planned', max_length=20)),
                ('content_link', models.URLField(blank=True, null=True)),
                ('scheduled_date', models.DateField(blank=True, null=True)),
                ('published_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand_strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.brandplatformstrategy')),
            ],
        ),
    ]
