# Generated by Django 5.2.5 on 2025-08-31 16:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientPlatformProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('website_blogs', 'Website Blogs'), ('website_downloadable', 'Website Downloadable'), ('google_business', 'Google Business'), ('linkedin', 'LinkedIn'), ('youtube', 'YouTube'), ('tiktok', 'TikTok'), ('instagram', 'Instagram'), ('pinterest', 'Pinterest'), ('twitter', 'Twitter/X'), ('facebook', 'Facebook'), ('medium', 'Medium'), ('tumblr', 'Tumblr'), ('threads', 'Threads'), ('quora', 'Quora'), ('reddit', 'Reddit'), ('bluesky', 'Blue Sky'), ('email_marketing', 'Email Marketing'), ('twitch', 'Twitch'), ('bereal', 'BeReal'), ('vimeo', 'Vimeo'), ('dailymotion', 'Daily Motion'), ('rumble', 'Rumble')], max_length=50)),
                ('committed', models.IntegerField(default=0, help_text='Total content promised to client')),
                ('drafted', models.IntegerField(default=0, help_text='Content currently drafted')),
                ('published', models.IntegerField(default=0, help_text='Content completed and published')),
                ('notes', models.TextField(blank=True, help_text='Internal notes for this platform')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Client Platform Progress',
                'verbose_name_plural': 'Client Platform Progress',
                'unique_together': {('user', 'platform')},
            },
        ),
        migrations.CreateModel(
            name='ContentLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Description of this link (e.g., 'Content Calendar', 'Draft Folder')", max_length=200)),
                ('url', models.URLField(help_text='Google Doc, Drive folder, or any resource URL')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('platform_progress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_links', to='dashboard.clientplatformprogress')),
            ],
            options={
                'verbose_name': 'Content Link',
                'verbose_name_plural': 'Content Links',
            },
        ),
        migrations.AlterUniqueTogether(
            name='brandplatformstrategy',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='brandplatformstrategy',
            name='platform',
        ),
        migrations.RemoveField(
            model_name='brandplatformstrategy',
            name='user',
        ),
        migrations.RemoveField(
            model_name='contentpiece',
            name='brand_strategy',
        ),
        migrations.DeleteModel(
            name='Hashtag',
        ),
        migrations.DeleteModel(
            name='Platform',
        ),
        migrations.DeleteModel(
            name='BrandPlatformStrategy',
        ),
        migrations.DeleteModel(
            name='ContentPiece',
        ),
    ]
