# Generated by Django 5.2.5 on 2025-09-06 18:15

from django.db import migrations, models
import django.db.models.deletion


def migrate_user_to_brand(apps, schema_editor):
    ClientPlatformProgress = apps.get_model('dashboard', 'ClientPlatformProgress')
    BrandProfile = apps.get_model('profiles', 'BrandProfile')
    
    for progress in ClientPlatformProgress.objects.all():
        try:
            brand = BrandProfile.objects.get(user=progress.user)
            progress.brand = brand
            progress.save()
        except BrandProfile.DoesNotExist:
            progress.delete()


def reverse_migrate_brand_to_user(apps, schema_editor):
    ClientPlatformProgress = apps.get_model('dashboard', 'ClientPlatformProgress')
    
    for progress in ClientPlatformProgress.objects.all():
        if progress.brand:
            progress.user = progress.brand.user
            progress.save()


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_clientplatformprogress_contentlink_and_more'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        # Step 1: Remove the old unique constraint first
        migrations.AlterUniqueTogether(
            name='clientplatformprogress',
            unique_together=set(),
        ),
        # Step 2: Add brand field as nullable
        migrations.AddField(
            model_name='clientplatformprogress',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='platform_progress', to='profiles.brandprofile'),
        ),
        # Step 3: Populate brand field from existing user data
        migrations.RunPython(migrate_user_to_brand, reverse_migrate_brand_to_user),
        # Step 4: Make brand field non-nullable
        migrations.AlterField(
            model_name='clientplatformprogress',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_progress', to='profiles.brandprofile'),
        ),
        # Step 5: Remove user field
        migrations.RemoveField(
            model_name='clientplatformprogress',
            name='user',
        ),
        # Step 6: Add new unique constraint with brand
        migrations.AlterUniqueTogether(
            name='clientplatformprogress',
            unique_together={('brand', 'platform')},
        ),
    ]
