# Generated by Django 5.2.5 on 2025-09-08 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20250906_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientplatformprogress',
            name='is_visible',
            field=models.BooleanField(default=True, help_text='Show this platform in dashboards'),
        ),
    ]
