# Generated by Django 5.2.5 on 2025-09-09 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_add_platform_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientplatformprogress',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Mark this platform as active or inactive'),
        ),
    ]
