# Generated by Django 5.2.5 on 2025-09-14 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_clientplatformprogress_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientplatformprogress',
            name='platform',
            field=models.CharField(choices=[('website_blogs', 'Website Blogs'), ('website_downloadable', 'Website Downloadable'), ('google_business', 'Google Business'), ('linkedin', 'LinkedIn'), ('youtube', 'YouTube'), ('tiktok', 'TikTok'), ('instagram', 'Instagram'), ('pinterest', 'Pinterest'), ('twitter', 'Twitter/X'), ('facebook', 'Facebook'), ('medium', 'Medium'), ('tumblr', 'Tumblr'), ('threads', 'Threads'), ('quora', 'Quora'), ('reddit', 'Reddit'), ('bluesky', 'Blue Sky'), ('email_marketing', 'Email Marketing'), ('twitch', 'Twitch'), ('bereal', 'BeReal'), ('vimeo', 'Vimeo'), ('dailymotion', 'Daily Motion'), ('rumble', 'Rumble'), ('linktree', 'Linktree')], max_length=50),
        ),
    ]
